_target_: src.models.timm_classifier.TimmClassifier

# Model parameters
base_model: resnet18
num_classes: 2
pretrained: true

# Optimizer parameters
lr: 1e-3
betas: [0.9, 0.999]
eps: 1e-8
weight_decay: 0.0
amsgrad: false

# Scheduler parameters
scheduler_factor: 0.1
scheduler_patience: 10
scheduler_threshold: 1e-4
scheduler_cooldown: 0
scheduler_min_lr: 0.0
