# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: catdog
  - model: timm_classify
  - callbacks: default
  - logger: null # set logger here or use command line (e.g. `python eval.py logger=tensorboard`)
  - trainer: default
  - paths: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # debugging config (enable through command line, e.g. `python eval.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "eval"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python eval.py tags="[first_tag, second_tag]"`
tags: ["eval"]

# set False to skip model training (not applicable for evaluation)
train: False

# evaluate on test set, using the provided checkpoint
test: True

# provide checkpoint path for evaluation
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null